import { 
    Home, Video, Image, Music, Mic, Bot, Sparkles, Settings, User, 
    Clapperboard, Film, Wand2, Layers, Type, ArrowRightLeft, ScanFace,
    Globe, Cpu, Monitor, Play, Pause, SkipBack, SkipForward, Volume2,
    VolumeX, Maximize, Minimize, ChevronLeft, ChevronRight,
    ChevronUp, ChevronDown, Plus, Minus, X, Check, Search, Bell, Star,
    Heart, MessageCircle, MessageSquare, Share2, Download, Upload, Trash2, Edit, Copy,
    ClipboardPaste, Save, Folder, File, FolderOpen, FileText, FileImage, FileVideo,
    FileAudio, FileCode, FilePlus, FolderPlus, RefreshCw, RotateCcw,
    ZoomIn, ZoomOut, Move, MousePointer, Hand, Grid, List, Filter,
    SortAsc, SortDesc, MoreHorizontal, MoreVertical, Menu, Sidebar,
    PanelLeft, PanelRight, AlignLeft, AlignCenter, AlignRight, AlignJustify,
    Bold, Italic, Underline, Strikethrough, Link, Unlink, Code, Quote,
    ListOrdered, ListChecks, Indent, Outdent, Table, Image as ImageIcon,
    Video as VideoIcon, AudioLines, Subtitles, Captions, Timer, Clock,
    Calendar, MapPin, Tag, Hash, AtSign, Mail, Phone, Globe as GlobeIcon,
    Lock, Unlock, Eye, EyeOff, Shield, ShieldCheck, ShieldAlert, AlertCircle,
    AlertTriangle, Info, HelpCircle, FileQuestion, CheckCircle, XCircle,
    Wifi, WifiOff, Bluetooth, Battery, BatteryLow, BatteryCharging,
    Sun, Moon, Cloud, CloudRain, CloudSnow, Wind, Thermometer, Droplet,
    Flame, Zap, Target, Crosshair, Focus, Aperture, Camera, CameraOff,
    Mic as MicIcon, MicOff, Headphones, Speaker, Radio, Tv, Cast,
    Smartphone, Tablet, Laptop, Monitor as DesktopIcon, Server, HardDrive, Database,
    CloudUpload, CloudDownload, CloudOff, Repeat,
    Shuffle, Play as PlayIcon, Pause as PauseIcon, Square, Circle,
    FastForward, Rewind, Volume1, Volume2 as Volume2Icon, VolumeX as VolumeXIcon,
    BookOpen, Library, LayoutDashboard, Palette, Scissors, Smile, AudioWaveform, Mic2, Presentation,
    LucideIcon
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
    home: Home,
    video: Video,
    image: Image,
    music: Music,
    mic: Mic,
    bot: Bot,
    sparkles: Sparkles,
    settings: Settings,
    user: User,
    clapperboard: Clapperboard,
    film: Film,
    wand: Wand2,
    layers: Layers,
    type: Type,
    'arrow-right-left': ArrowRightLeft,
    'scan-face': ScanFace,
    globe: Globe,
    cpu: Cpu,
    monitor: Monitor,
    play: Play,
    pause: Pause,
    'skip-back': SkipBack,
    'skip-forward': SkipForward,
    'volume-2': Volume2,
    'volume-x': VolumeX,
    maximize: Maximize,
    minimize: Minimize,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'chevron-down': ChevronDown,
    plus: Plus,
    minus: Minus,
    x: X,
    check: Check,
    search: Search,
    bell: Bell,
    star: Star,
    heart: Heart,
    'message-circle': MessageCircle,
    'message-square': MessageSquare,
    share: Share2,
    download: Download,
    upload: Upload,
    trash: Trash2,
    edit: Edit,
    copy: Copy,
    paste: ClipboardPaste,
    save: Save,
    folder: Folder,
    file: File,
    'folder-open': FolderOpen,
    'file-text': FileText,
    'file-image': FileImage,
    'file-video': FileVideo,
    'file-audio': FileAudio,
    'file-code': FileCode,
    'file-plus': FilePlus,
    'folder-plus': FolderPlus,
    refresh: RefreshCw,
    rotate: RotateCcw,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
    move: Move,
    'mouse-pointer': MousePointer,
    hand: Hand,
    grid: Grid,
    list: List,
    filter: Filter,
    'sort-asc': SortAsc,
    'sort-desc': SortDesc,
    'more-horizontal': MoreHorizontal,
    'more-vertical': MoreVertical,
    menu: Menu,
    sidebar: Sidebar,
    'panel-left': PanelLeft,
    'panel-right': PanelRight,
    'align-left': AlignLeft,
    'align-center': AlignCenter,
    'align-right': AlignRight,
    'align-justify': AlignJustify,
    bold: Bold,
    italic: Italic,
    underline: Underline,
    strikethrough: Strikethrough,
    link: Link,
    unlink: Unlink,
    code: Code,
    quote: Quote,
    'list-ordered': ListOrdered,
    'list-unordered': ListChecks,
    indent: Indent,
    outdent: Outdent,
    table: Table,
    'image-icon': ImageIcon,
    'video-icon': VideoIcon,
    'audio-lines': AudioLines,
    subtitles: Subtitles,
    caption: Captions,
    timer: Timer,
    clock: Clock,
    calendar: Calendar,
    'map-pin': MapPin,
    tag: Tag,
    hash: Hash,
    'at-sign': AtSign,
    mail: Mail,
    phone: Phone,
    'globe-icon': GlobeIcon,
    lock: Lock,
    unlock: Unlock,
    eye: Eye,
    'eye-off': EyeOff,
    shield: Shield,
    'shield-check': ShieldCheck,
    'shield-alert': ShieldAlert,
    'alert-circle': AlertCircle,
    'alert-triangle': AlertTriangle,
    info: Info,
    'help-circle': HelpCircle,
    'question-mark': FileQuestion,
    'check-circle': CheckCircle,
    'x-circle': XCircle,
    wifi: Wifi,
    'wifi-off': WifiOff,
    bluetooth: Bluetooth,
    battery: Battery,
    'battery-low': BatteryLow,
    'battery-charging': BatteryCharging,
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    wind: Wind,
    thermometer: Thermometer,
    droplet: Droplet,
    flame: Flame,
    zap: Zap,
    target: Target,
    crosshair: Crosshair,
    focus: Focus,
    aperture: Aperture,
    camera: Camera,
    'camera-off': CameraOff,
    'mic-icon': MicIcon,
    'mic-off': MicOff,
    headphones: Headphones,
    speaker: Speaker,
    radio: Radio,
    tv: Tv,
    cast: Cast,
    smartphone: Smartphone,
    tablet: Tablet,
    laptop: Laptop,
    desktop: DesktopIcon,
    server: Server,
    'hard-drive': HardDrive,
    database: Database,
    'cloud-upload': CloudUpload,
    'cloud-download': CloudDownload,
    'cloud-off': CloudOff,
    repeat: Repeat,
    shuffle: Shuffle,
    'play-icon': PlayIcon,
    'pause-icon': PauseIcon,
    stop: Square,
    record: Circle,
    'fast-forward': FastForward,
    rewind: Rewind,
    'volume-1': Volume1,
    'volume-2-icon': Volume2Icon,
    'volume-x-icon': VolumeXIcon,
    mute: VolumeX,
    'book-open': BookOpen,
    library: Library,
    'layout-dashboard': LayoutDashboard,
    palette: Palette,
    scissors: Scissors,
    smile: Smile,
    'audio-waveform': AudioWaveform,
    'mic-2': Mic2,
    presentation: Presentation,
};

export function getIconComponent(iconName: string): LucideIcon | null {
    return iconMap[iconName.toLowerCase()] || null;
}

export { iconMap };
