import assert from 'node:assert/strict';
import test from 'node:test';

import {
  normalizeModuleId,
  resolveExternalSdkChunk,
  resolveAssetsFeatureChunk,
  resolveFilmFeatureChunk,
  resolveMagicCutFeatureChunk,
  resolveVendorChunk,
  resolveManualChunk,
} from '../scripts/vite-manual-chunks.mjs';

test('normalizeModuleId normalizes windows separators for stable chunk routing', () => {
  assert.equal(
    normalizeModuleId('D:\\repo\\packages\\sdkwork-magic-studio-assets\\src\\pages\\AssetsPage.tsx'),
    'D:/repo/packages/sdkwork-magic-studio-assets/src/pages/AssetsPage.tsx',
  );
});

test('resolveAssetsFeatureChunk splits assets package by responsibility', () => {
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/pages/AssetsPage.tsx'),
    'feature-assets-center',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/components/generate/GenerationChatWindow.tsx'),
    'feature-assets-generation',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/components/ChooseAssetModal.tsx'),
    'feature-assets-generation',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/style-selector/index.ts'),
    'feature-assets-generation',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/services/generatedOutcomeAssetPersistence.ts'),
    'feature-assets-services',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/asset-service/index.ts'),
    'feature-assets-services',
  );
  assert.equal(
    resolveAssetsFeatureChunk('/repo/packages/sdkwork-magic-studio-assets/src/index.ts'),
    'feature-assets-shared',
  );
});

test('resolveFilmFeatureChunk separates film pages, modals, and core modules', () => {
  assert.equal(
    resolveFilmFeatureChunk('/repo/packages/sdkwork-magic-studio-film/src/pages/FilmHomePage.tsx'),
    'feature-film-pages',
  );
  assert.equal(
    resolveFilmFeatureChunk('/repo/packages/sdkwork-magic-studio-film/src/components/ShotModal.tsx'),
    'feature-film-modals',
  );
  assert.equal(
    resolveFilmFeatureChunk('/repo/packages/sdkwork-magic-studio-film/src/store/filmStore.tsx'),
    'feature-film-core',
  );
});

test('resolveExternalSdkChunk isolates aliased app sdk and sdk-common sources into shared chunks', () => {
  assert.equal(
    resolveExternalSdkChunk(
      '/repo/spring-ai-plus-business/spring-ai-plus-app-api/sdkwork-sdk-app/sdkwork-app-sdk-typescript/src/api/voice-speaker.ts',
    ),
    'shared-app-sdk',
  );
  assert.equal(
    resolveExternalSdkChunk(
      '/repo/spring-ai-plus-business/sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript/src/index.ts',
    ),
    'shared-sdk-common',
  );
  assert.equal(
    resolveExternalSdkChunk('/repo/packages/sdkwork-magic-studio-assets/src/pages/AssetsPage.tsx'),
    undefined,
  );
});

test('resolveMagicCutFeatureChunk separates shell, panels, and render engine modules', () => {
  assert.equal(
    resolveMagicCutFeatureChunk('/repo/packages/sdkwork-magic-studio-magiccut/src/pages/MagicCutPage.tsx'),
    'feature-magiccut-shell',
  );
  assert.equal(
    resolveMagicCutFeatureChunk('/repo/packages/sdkwork-magic-studio-magiccut/src/components/Resources/MagicCutResourcePanel.tsx'),
    'feature-magiccut-panels',
  );
  assert.equal(
    resolveMagicCutFeatureChunk('/repo/packages/sdkwork-magic-studio-magiccut/src/engine/WebGLEngine.ts'),
    'feature-magiccut-engine',
  );
});

test('resolveVendorChunk separates heavy node_modules families into stable vendor groups', () => {
  assert.equal(
    resolveVendorChunk('/repo/node_modules/react/index.js'),
    'vendor-react',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/react-dom/client.js'),
    'vendor-react',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/react-router-dom/dist/index.js'),
    'vendor-react',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@remix-run/router/dist/router.js'),
    'vendor-react',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@radix-ui/react-dialog/dist/index.mjs'),
    'vendor-ui',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/lucide-react/dist/esm/icons/x.js'),
    'vendor-ui',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@monaco-editor/react/dist/index.mjs'),
    'vendor-editor',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/monaco-editor/esm/vs/editor/editor.api.js'),
    'vendor-editor',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@tiptap/react/dist/index.js'),
    'vendor-editor',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@xterm/xterm/lib/xterm.js'),
    'vendor-editor',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@aws-sdk/client-s3/dist/index.js'),
    'vendor-aws',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/@smithy/core/dist/index.js'),
    'vendor-aws',
  );
  assert.equal(
    resolveVendorChunk('/repo/node_modules/zustand/esm/index.mjs'),
    'vendor',
  );
  assert.equal(
    resolveVendorChunk('/repo/src/app/App.tsx'),
    undefined,
  );
});

test('resolveManualChunk keeps vendor handling granular and routes heavy features into finer chunks', () => {
  assert.equal(
    resolveManualChunk('/repo/node_modules/react/index.js'),
    'vendor-react',
  );
  assert.equal(
    resolveManualChunk('/repo/node_modules/@radix-ui/react-dialog/dist/index.mjs'),
    'vendor-ui',
  );
  assert.equal(
    resolveManualChunk('/repo/node_modules/@monaco-editor/react/dist/index.mjs'),
    'vendor-editor',
  );
  assert.equal(
    resolveManualChunk('/repo/node_modules/@aws-sdk/client-s3/dist/index.js'),
    'vendor-aws',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-commons/src/index.ts'),
    'shared-magic-studio-commons',
  );
  assert.equal(
    resolveManualChunk(
      '/repo/spring-ai-plus-business/spring-ai-plus-app-api/sdkwork-sdk-app/sdkwork-app-sdk-typescript/src/api/voice-speaker.ts',
    ),
    'shared-app-sdk',
  );
  assert.equal(
    resolveManualChunk(
      '/repo/spring-ai-plus-business/sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript/src/index.ts',
    ),
    'shared-sdk-common',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-core/src/router/index.ts'),
    'shared-magic-studio-core',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-i18n/src/I18nService.ts'),
    'shared-magic-studio-i18n',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-i18n/src/resources/en.ts'),
    'shared-magic-studio-i18n-en',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-i18n/src/locales/en/index.ts'),
    'shared-magic-studio-i18n-en',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-i18n/src/resources/zh-CN.ts'),
    'shared-magic-studio-i18n-zh-cn',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-i18n/src/locales/zh-CN/index.ts'),
    'shared-magic-studio-i18n-zh-cn',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-types/src/index.ts'),
    'shared-magic-studio-types',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-assets/src/components/generate/PromptTextInput.tsx'),
    'feature-assets-generation',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-film/src/components/SceneModal.tsx'),
    'feature-film-modals',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-magiccut/src/components/Player/UniversalPlayer.tsx'),
    'feature-magiccut-engine',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-image/src/pages/ImagePage.tsx'),
    'feature-image',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-video/src/components/VideoLeftGeneratorPanel.tsx'),
    'feature-video',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-audio/src/pages/AudioChatPage.tsx'),
    'feature-audio',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-music/src/components/MusicLeftGeneratorPanel.tsx'),
    'feature-music',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-sfx/src/components/SfxGeneratorModal.tsx'),
    'feature-sfx',
  );
  assert.equal(
    resolveManualChunk('/repo/packages/sdkwork-magic-studio-voicespeaker/src/pages/VoicePage.tsx'),
    'feature-voice-speaker',
  );
  assert.equal(
    resolveManualChunk('/repo/src/app/App.tsx'),
    undefined,
  );
});

