import type { StyleOption } from '../types';

const buildStyle = (
  id: string,
  label: string,
  description: string,
  prompt: string,
  previewColor: string,
  isCustom = false,
): StyleOption => ({
  id,
  label,
  description,
  prompt,
  prompt_zh: '',
  previewColor,
  isCustom,
});

const BASE_STYLES: StyleOption[] = [
  buildStyle(
    'cinematic',
    'Cinematic',
    'Hollywood blockbuster lighting, depth, and dramatic framing.',
    'cinematic lighting, depth of field, movie still, color graded, atmospheric, anamorphic lens, film grain',
    '#d97706',
  ),
  buildStyle(
    'high_sat_real',
    'High Saturation',
    'Vivid and energetic realism with bright contrast.',
    'high saturation, vibrant realism, crisp focus, bright commercial lighting, colorful modern life',
    '#f97316',
  ),
  buildStyle(
    'aesthetic_real',
    'Aesthetic',
    'Soft and dreamy realism with polished beauty.',
    'soft light, dreamy atmosphere, clean realism, elegant composition, gentle colors, aesthetic editorial look',
    '#ec4899',
  ),
  buildStyle(
    'retro_dv',
    'Retro DV',
    'Lo-fi handheld camcorder mood with nostalgic grain.',
    'retro DV camcorder, VHS noise, low fidelity, timestamp, handheld motion, home video nostalgia',
    '#8b5cf6',
  ),
  buildStyle(
    'bw_film',
    'B&W Film',
    'High-contrast monochrome storytelling.',
    'black and white film photography, dramatic contrast, classic cinema lighting, silver grain',
    '#6b7280',
  ),
  buildStyle(
    'wkw_style',
    'WKW Style',
    'Step-printed neon melancholy and urban romance.',
    'neon color palette, motion blur, step printing, moody city nights, Wong Kar-wai inspired',
    '#ef4444',
  ),
  buildStyle(
    'iwai_style',
    'Iwai Style',
    'Overexposed, youthful, and delicate Japanese film mood.',
    'overexposed highlights, soft focus, youthful atmosphere, natural light, delicate Japanese cinema',
    '#f59e0b',
  ),
  buildStyle(
    'japanese_anime',
    'Anime',
    'Modern Japanese animation with rich skies and detail.',
    'Japanese anime, detailed background art, vibrant sky, polished 2D rendering, emotional storytelling',
    '#3b82f6',
  ),
  buildStyle(
    'chinese_comic',
    'CN Comic',
    'Chinese fantasy comic styling with flowing costume detail.',
    'Chinese comic art, xianxia fantasy, elegant line work, flowing robes, stylized illustration',
    '#14b8a6',
  ),
  buildStyle(
    'korean_manhwa',
    'Manhwa',
    'Glossy webtoon aesthetic with stylish characters.',
    'Korean manhwa, high saturation, clean line art, fashionable character design, vertical composition',
    '#ec4899',
  ),
  buildStyle(
    'cel_shaded',
    'Cel Shaded',
    'Game-like 3D rendered with crisp anime-style shading.',
    'cel shaded rendering, anime game art, crisp shadows, bold colors, polished 3D to 2D style',
    '#f97316',
  ),
  buildStyle(
    'ghibli',
    'Ghibli',
    'Warm hand-painted fantasy with natural charm.',
    'hand painted animation, warm natural colors, whimsical fantasy, lush environment detail',
    '#22c55e',
  ),
  buildStyle(
    'ancient_2d',
    '2D Ancient',
    'Flat illustration inspired by classical scroll paintings.',
    'ancient Chinese illustration, flat composition, elegant lines, scroll painting atmosphere',
    '#a855f7',
  ),
  buildStyle(
    'ancient_3d',
    '3D Ancient',
    'Stylized historical fantasy with detailed CG costume work.',
    '3D ancient Chinese fantasy, rich costume detail, dramatic lighting, animated historical epic',
    '#f43f5e',
  ),
  buildStyle(
    'ancient_real',
    'Realistic Ancient',
    'Cinema-grade costume drama realism.',
    'realistic historical costume drama, detailed wardrobe, cinematic lighting, epic ancient setting',
    '#ca8a04',
  ),
  buildStyle(
    'gongbi',
    'Gongbi',
    'Meticulous traditional painting with refined ornament.',
    'gongbi painting, meticulous brushwork, traditional Chinese art, ornate detail, elegant color palette',
    '#0f766e',
  ),
  buildStyle(
    'sketch',
    'Sketch',
    'Pencil and charcoal linework with artistic restraint.',
    'pencil sketch, charcoal drawing, monochrome line art, textured paper, hand drawn illustration',
    '#64748b',
  ),
  buildStyle(
    'watercolor',
    'Watercolor',
    'Transparent washes and poetic color flow.',
    'watercolor illustration, wet-on-wet blending, soft pigment spread, airy and poetic mood',
    '#38bdf8',
  ),
  buildStyle(
    'oil_painting',
    'Oil Painting',
    'Expressive brushwork and rich pigment texture.',
    'oil painting texture, visible brush strokes, rich pigment, impressionist mood, canvas texture',
    '#f59e0b',
  ),
  buildStyle(
    'clay',
    'Clay',
    'Stop-motion crafted from handmade clay materials.',
    'clay animation, stop motion look, handmade texture, tactile surface, playful miniature world',
    '#ea580c',
  ),
  buildStyle(
    'felt',
    'Felt Art',
    'Soft wool texture with cozy handcrafted warmth.',
    'felt craft, wool texture, fuzzy edges, handmade softness, cozy handcrafted illustration',
    '#16a34a',
  ),
  buildStyle(
    'lego',
    'Lego',
    'Glossy brick-built miniature scenes.',
    'building block world, glossy plastic texture, miniature photography, toy design, interlocking bricks',
    '#eab308',
  ),
  buildStyle(
    '3d_cartoon',
    '3D Cartoon',
    'Rounded family-friendly stylized animation.',
    '3D cartoon rendering, rounded forms, clean materials, bright family-friendly animation',
    '#06b6d4',
  ),
  buildStyle(
    'pixar',
    'Pixar',
    'Premium animated feature quality with expressive characters.',
    'feature animation quality, expressive faces, subsurface scattering, polished cinematic 3D render',
    '#fb7185',
  ),
  buildStyle(
    'cyberpunk',
    'Cyberpunk',
    'Rain-soaked neon futurism with intense contrast.',
    'cyberpunk city, neon reflections, wet streets, holograms, futuristic nightlife, high contrast',
    '#8b5cf6',
  ),
  buildStyle(
    'futurism',
    'Futurism',
    'Clean metallic sci-fi with optimistic technology vibes.',
    'futuristic design, metallic surfaces, sleek geometry, clean sci-fi composition, optimistic high tech',
    '#3b82f6',
  ),
  buildStyle(
    'y2k',
    'Y2K',
    'Millennium pop futurism with chrome and glow.',
    'Y2K aesthetic, chrome shine, fluorescent accents, digital nostalgia, collage-like pop styling',
    '#e879f9',
  ),
  buildStyle(
    'kpop',
    'K-pop',
    'Stage-lit pop glamour with glossy styling.',
    'K-pop performance, stage lights, glossy fashion styling, energetic music video atmosphere',
    '#f43f5e',
  ),
  buildStyle(
    'city_pop_urban',
    'City Pop Urban',
    'Retro metropolitan nightlife with neon warmth.',
    'city pop urban night, neon signage, retro city glow, relaxed 1980s nightlife, stylish streets',
    '#0ea5e9',
  ),
  buildStyle(
    'city_pop_anime',
    'City Pop Anime',
    'Vintage OVA-inspired anime nostalgia.',
    'city pop anime, retro OVA style, soft cel colors, nostalgic urban nightscape, hand drawn feel',
    '#6366f1',
  ),
  buildStyle(
    'custom',
    'Custom',
    'Do not apply a preset style.',
    '',
    '#6b7280',
    true,
  ),
];

export const IMAGE_STYLES: StyleOption[] = BASE_STYLES.map((style) => ({ ...style }));

export const VIDEO_STYLES: StyleOption[] = BASE_STYLES.map((style) => ({ ...style }));
