
export const ROUTES = {
  HOME: '/',
  EDITOR: '/editor',
  CHAT: '/chat',
  BROWSER: '/browser',
  DRIVE: '/drive',
  NOTES: '/notes',
  ASSETS: '/assets',
  IMAGE: '/image',
  IMAGE_CHAT: '/image/chat',
  VIDEO: '/video',
  VIDEO_CHAT: '/video/chat',
  MUSIC: '/music',
  MUSIC_CHAT: '/music/chat',
  SFX: '/sfx',
  SFX_CHAT: '/sfx/chat',
  VOICE: '/voice',
  VOICE_CHAT: '/voice/chat',
  AUDIO: '/audio',
  AUDIO_CHAT: '/audio/chat',
  CHARACTER: '/character',
  CHARACTER_CHAT: '/character/chat',
  CHAT_PPT: '/chat-ppt',
  CANVAS: '/canvas',
  MAGIC_CUT: '/magic-cut',
  FILM: '/film',
  FILM_EDITOR: '/film/editor',
  PROMPT: '/prompt',
  PORTAL: '/portal',
  PORTAL_VIDEO: '/portal/video',
  PORTAL_TOOLS: '/portal/tools',
  PORTAL_DISCOVER: '/portal/discover',
  PORTAL_COMMUNITY: '/portal/community',
  PORTAL_THEATER: '/portal/theater',
  PORTAL_SKILLS: '/portal/skills',
  PORTAL_SKILLS_DETAIL: '/portal/skills/:skillId',
  PORTAL_PLUGINS: '/portal/plugins',
  SETTINGS: '/settings',
  LOGIN: '/login',
  PROFILE: '/profile',
  VIP: '/vip',
  TASK_MARKET: '/task-market',
  MY_TASKS: '/my-tasks',
  DOWNLOAD: '/app/download',
} as const;

export type RoutePath = typeof ROUTES[keyof typeof ROUTES];
