import { ROUTES } from '../routes';
import type { RouteSpec } from './types';

export const mainRouteSpecs = [
  { path: ROUTES.HOME, componentKey: 'home', layout: 'none' },
  {
    path: ROUTES.EDITOR,
    componentKey: 'editor',
    layout: 'main',
    providerKey: 'editor',
    preload: ['drive', 'assets', 'notes', 'chatppt'],
  },
  { path: ROUTES.CHAT, componentKey: 'chat', layout: 'none' },
  { path: ROUTES.BROWSER, componentKey: 'browser', layout: 'main' },
  {
    path: ROUTES.DRIVE,
    componentKey: 'drive',
    layout: 'creation',
    preload: ['editor', 'assets', 'notes'],
  },
  {
    path: ROUTES.ASSETS,
    componentKey: 'assets',
    layout: 'creation',
    providerKey: 'assets',
    preload: ['image', 'video', 'magiccut'],
  },
  { path: ROUTES.SETTINGS, componentKey: 'settings', layout: 'none' },
  { path: ROUTES.PROFILE, componentKey: 'profile', layout: 'none' },
  { path: ROUTES.VIP, componentKey: 'pricing', layout: 'main' },
  {
    path: ROUTES.NOTES,
    componentKey: 'notes',
    layout: 'notes',
    preload: ['assets', 'image', 'drive'],
  },
  { path: ROUTES.LOGIN, componentKey: 'login', layout: 'none' },
  { path: ROUTES.AUTH_LOGIN, componentKey: 'login', layout: 'none' },
  { path: ROUTES.AUTH_REGISTER, componentKey: 'login', layout: 'none' },
  { path: ROUTES.AUTH_FORGOT_PASSWORD, componentKey: 'login', layout: 'none' },
  {
    path: ROUTES.AUTH_OAUTH_CALLBACK,
    componentKey: 'authOAuthCallback',
    layout: 'none',
  },
] as const satisfies readonly RouteSpec[];

export const generationRouteSpecs = [
  {
    path: ROUTES.IMAGE,
    componentKey: 'image',
    layout: 'generation',
    leftPaneKey: 'image',
    providerKey: 'image',
    preload: ['video', 'assets', 'magiccut'],
  },
  { path: ROUTES.IMAGE_CHAT, componentKey: 'imageChat', layout: 'none' },
  {
    path: ROUTES.VIDEO,
    componentKey: 'video',
    layout: 'generation',
    leftPaneKey: 'video',
    providerKey: 'video',
    preload: ['image', 'assets', 'magiccut'],
  },
  { path: ROUTES.VIDEO_CHAT, componentKey: 'videoChat', layout: 'none' },
  {
    path: ROUTES.MUSIC,
    componentKey: 'music',
    layout: 'generation',
    leftPaneKey: 'music',
    providerKey: 'music',
    preload: ['assets', 'magiccut', 'video'],
  },
  { path: ROUTES.MUSIC_CHAT, componentKey: 'musicChat', layout: 'none' },
  {
    path: ROUTES.SFX,
    componentKey: 'sfx',
    layout: 'generation',
    leftPaneKey: 'sfx',
    providerKey: 'sfx',
    preload: ['assets', 'magiccut', 'video'],
  },
  { path: ROUTES.SFX_CHAT, componentKey: 'sfxChat', layout: 'none' },
  {
    path: ROUTES.VOICE,
    componentKey: 'voice',
    layout: 'generation',
    leftPaneKey: 'voice',
    providerKey: 'voice',
    preload: ['assets', 'magiccut', 'video'],
  },
  { path: ROUTES.VOICE_CHAT, componentKey: 'voiceChat', layout: 'none' },
  {
    path: ROUTES.AUDIO,
    componentKey: 'audio',
    layout: 'generation',
    leftPaneKey: 'audio',
    providerKey: 'audio',
    preload: ['assets', 'magiccut', 'video'],
  },
  { path: ROUTES.AUDIO_CHAT, componentKey: 'audioChat', layout: 'none' },
  {
    path: ROUTES.CHARACTER,
    componentKey: 'character',
    layout: 'generation',
    leftPaneKey: 'character',
    providerKey: 'character',
    preload: ['voice', 'video', 'assets'],
  },
  {
    path: ROUTES.CHARACTER_CHAT,
    componentKey: 'characterChat',
    layout: 'generation',
    providerKey: 'character',
  },
] as const satisfies readonly RouteSpec[];

export const advancedRouteSpecs = [
  {
    path: ROUTES.CHAT_PPT,
    componentKey: 'chatPpt',
    layout: 'vibe',
    leftPaneKey: 'chatPpt',
    providerKey: 'chatPpt',
    preload: ['editor', 'drive', 'canvas'],
  },
  { path: ROUTES.CANVAS, componentKey: 'canvas', layout: 'none' },
  {
    path: ROUTES.MAGIC_CUT,
    componentKey: 'magicCut',
    layout: 'magic-cut',
    providerKey: 'magicCut',
    preload: ['assets', 'video', 'audio', 'music'],
  },
  {
    path: ROUTES.FILM,
    componentKey: 'filmHome',
    layout: 'none',
    preload: ['assets', 'image', 'video', 'magiccut'],
  },
  { path: ROUTES.FILM_EDITOR, componentKey: 'filmEditor', layout: 'none' },
  { path: ROUTES.PROMPT, componentKey: 'promptOptimizer', layout: 'none' },
  {
    path: ROUTES.PORTAL,
    componentKey: 'portal',
    layout: 'none',
    preload: ['portal-video', 'skills', 'plugins', 'film'],
  },
  { path: ROUTES.PORTAL_VIDEO, componentKey: 'portalVideo', layout: 'none' },
  { path: ROUTES.PORTAL_TOOLS, componentKey: 'portalTools', layout: 'none' },
  { path: ROUTES.PORTAL_DISCOVER, componentKey: 'portalDiscover', layout: 'none' },
  {
    path: ROUTES.PORTAL_COMMUNITY,
    componentKey: 'portalCommunity',
    layout: 'none',
  },
  { path: ROUTES.PORTAL_THEATER, componentKey: 'portalTheater', layout: 'none' },
  { path: ROUTES.PORTAL_SKILLS, componentKey: 'portalSkills', layout: 'none' },
  {
    path: ROUTES.PORTAL_SKILLS_DETAIL,
    componentKey: 'portalSkillDetail',
    layout: 'none',
  },
  { path: ROUTES.PORTAL_PLUGINS, componentKey: 'portalPlugins', layout: 'none' },
  {
    path: ROUTES.TASK_MARKET,
    componentKey: 'taskMarket',
    layout: 'none',
    preload: ['portal-video', 'film', 'assets'],
  },
  {
    path: ROUTES.MY_TASKS,
    componentKey: 'myTasks',
    layout: 'none',
    preload: ['portal-video', 'film', 'assets'],
  },
  { path: ROUTES.DOWNLOAD, componentKey: 'download', layout: 'none' },
] as const satisfies readonly RouteSpec[];

export const routeSpecs = [
  ...mainRouteSpecs,
  ...generationRouteSpecs,
  ...advancedRouteSpecs,
] as const satisfies readonly RouteSpec[];
