upstream res_cluster {
    server localhost:8901 max_fails=3 weight=5;
}
server {
       listen       443 ssl;
       server_name  res.noaper.com ~^(res[a-zA-Z0-9]+|res_[a-zA-Z]+).noaper.com$;
       #ssl on;
       ssl_certificate /opt/certs/letsencrypt/live/noaper.com/fullchain.pem;
       ssl_certificate_key /opt/certs/letsencrypt/live/noaper.com/privkey.pem;
       ssl_session_timeout 5m;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
       ssl_prefer_server_ciphers on;
       location ~* ^.+\.(mp4|avi|mkv|mov|wmv|flv|webm|mpeg|mpg|3gp|3g2|ogv|vob|mts|m2ts|f4v|rmvb|ts|mp3|css|js|txt|xml|swf|wav|png|gif|jpg|jpeg|eot|otf|ttf|woff|woff2|eot|svg)$ {
          set $cors "";
          if ($http_origin ~* ^https?://([^/]+\.)?noaper\.com$) {
            set $cors "true";
          }

           # 设置 CORS 头
          if ($cors = "true") {
            add_header Access-Control-Allow-Origin *;#$http_origin;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
          }

          # 如果需要支持复杂请求（如 PUT, DELETE），可以添加以下配置
          if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;#$http_origin;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
            add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain charset=UTF-8';
            add_header Content-Length 0;
            return 204;
           }

               root   /data/resources;
        }


        location ~ /.well-known {
                allow all;
        }

}
server {
       listen       80;
       server_name  res.noaper.com ~^(res[a-zA-Z0-9]+|res_[a-zA-Z]+).noaper.com$;
       location ~* ^.+\.(mp4|avi|mkv|mov|wmv|flv|webm|mpeg|mpg|3gp|3g2|ogv|vob|mts|m2ts|f4v|rmvb|ts|mp3|css|js|txt|xml|swf|wav|png|gif|jpg|jpeg|eot|otf|ttf|woff|woff2|eot|svg)$ {
          set $cors "";
          if ($http_origin ~* ^https?://([^/]+\.)?noaper\.com$) {
            set $cors "true";
          }

           # 设置 CORS 头
          if ($cors = "true") {
            add_header Access-Control-Allow-Origin *;#$http_origin;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
          }

          # 如果需要支持复杂请求（如 PUT, DELETE），可以添加以下配置
          if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin *;#$http_origin;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
            add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain charset=UTF-8';
            add_header Content-Length 0;
            return 204;
           }
           root  /data/resources;
        }
       location ~ /.well-known {
            allow all;
       }
}