{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-runtime" .Release.Name }}
type: Opaque
stringData:
  MAGIC_STUDIO_USER_CENTER_DATABASE_URL: {{ .Values.secrets.userCenterDatabaseUrl | quote }}
  MAGIC_STUDIO_USER_CENTER_SHARED_SECRET: {{ .Values.secrets.userCenterSharedSecret | quote }}
{{- end }}
